set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME )
set(VCPKG_PLATFORM_TOOLSET v143)
set(VCPKG_LOAD_VCVARS_ENV ON)

list(APPEND VCPKG_ENV_PASSTHROUGH Qt6_DIR)
