/// @file
/// @brief Stable identifiers and lookup keys for shader entries inside a ShaderArchive.
///        Editor and runtime share the same encoding so a permutation key generated by
///        either side addresses the same archive entry.

#pragma once

#include "Core/Utils/Hash.h"
#include "RHI/RHIEnums.h"

#include <cstdint>

namespace Hylux::Shader
{

/// @brief Top-level taxonomy used by the archive's two index tables.
enum class ShaderCategory : std::uint8_t
{
    Pass     = 0,
    Material = 1,
};

/// @brief Composite lookup key for a pass shader entry. The triple (name, permutation,
///        stage) uniquely identifies a row in the pass shader index.
struct PassShaderKey
{
    std::uint64_t    passNameHash{0};
    std::uint64_t    permutationKey{0};
    RHI::ShaderStage stage{RHI::ShaderStage::None};
};

/// @brief Composite lookup key for a material shader entry. The quintuple (material asset,
///        pass id, permutation, stage) uniquely identifies a row in the material index.
struct MaterialShaderKey
{
    std::uint64_t    materialAssetHash{0};
    std::uint64_t    passIdHash{0};
    std::uint64_t    permutationKey{0};
    RHI::ShaderStage stage{RHI::ShaderStage::None};
};

/// @brief Opaque 64-bit identifier derived from a PassShaderKey or MaterialShaderKey.
///        Stable across archive reloads as long as the underlying key components match.
struct ShaderId
{
    std::uint64_t value{0};

    [[nodiscard]] friend constexpr bool operator==(ShaderId a, ShaderId b) noexcept
    {
        return a.value == b.value;
    }
    [[nodiscard]] friend constexpr bool operator!=(ShaderId a, ShaderId b) noexcept
    {
        return a.value != b.value;
    }
};

/// @brief Computes the ShaderId for a pass shader entry.
[[nodiscard]] inline ShaderId MakeShaderId(const PassShaderKey& key) noexcept
{
    std::uint64_t h = Hash::Fnv1a64Offset;
    h = Hash::MixU8(h, static_cast<std::uint8_t>(ShaderCategory::Pass));
    h = Hash::MixU64(h, key.passNameHash);
    h = Hash::MixU64(h, key.permutationKey);
    h = Hash::MixU32(h, static_cast<std::uint32_t>(key.stage));
    return ShaderId{h};
}

/// @brief Computes the ShaderId for a material shader entry.
[[nodiscard]] inline ShaderId MakeShaderId(const MaterialShaderKey& key) noexcept
{
    std::uint64_t h = Hash::Fnv1a64Offset;
    h = Hash::MixU8(h, static_cast<std::uint8_t>(ShaderCategory::Material));
    h = Hash::MixU64(h, key.materialAssetHash);
    h = Hash::MixU64(h, key.passIdHash);
    h = Hash::MixU64(h, key.permutationKey);
    h = Hash::MixU32(h, static_cast<std::uint32_t>(key.stage));
    return ShaderId{h};
}

} // namespace Hylux::Shader
