/// @file
/// @brief Picks which SIMD backend the L0 API compiles against.

#pragma once

#if defined(HYLUX_MATH_SIMD_BACKEND_EXT)
#if !defined(HYLUX_MATH_SIMD_EXTENSION_HEADER)
#error "HYLUX_MATH_SIMD_BACKEND_EXT=1 requires HYLUX_MATH_SIMD_EXTENSION_HEADER to be defined."
#endif
#define HYLUX_MATH_SIMD_BACKEND_NAME "EXT"
#elif defined(HYLUX_MATH_SIMD_BACKEND_SSE)
#define HYLUX_MATH_SIMD_BACKEND_NAME "SSE"
#elif defined(HYLUX_MATH_SIMD_BACKEND_NEON)
#define HYLUX_MATH_SIMD_BACKEND_NAME "NEON"
#elif defined(HYLUX_MATH_SIMD_BACKEND_SCALAR)
#define HYLUX_MATH_SIMD_BACKEND_NAME "SCALAR"
#else
#if defined(HYLUX_ARCH_X64)
#define HYLUX_MATH_SIMD_BACKEND_SSE 1
#define HYLUX_MATH_SIMD_BACKEND_NAME "SSE"
#elif defined(HYLUX_ARCH_ARM64)
#define HYLUX_MATH_SIMD_BACKEND_NEON 1
#define HYLUX_MATH_SIMD_BACKEND_NAME "NEON"
#else
#define HYLUX_MATH_SIMD_BACKEND_SCALAR 1
#define HYLUX_MATH_SIMD_BACKEND_NAME "SCALAR"
#endif
#endif
